import { appendFileSync, readFileSync, statSync } from 'node:fs'
import { resolve, relative, sep, join } from 'node:path'
import { defineTool } from '@deepseek-ai/dsh-tools'
import Schema from '@deepseek-ai/schemastery'

export const name = 'project-memory'
export const inject = ['tools', 'systemPrompt']

export const Config = Schema.object({
  fileName: Schema.string().default('MEMORY.md'),
  candidateFileName: Schema.string().default('.dsh-memory-candidates.md'),
  maxChars: Schema.number().min(500).max(20000).default(6000),
  maxMatches: Schema.number().min(1).max(20).default(6),
  lazyMode: Schema.boolean().default(true),
  maxCandidates: Schema.number().min(1).max(100).default(20),
  maxCandidateChars: Schema.number().min(1000).max(20000).default(6000),
})

function workspaceOf(context) {
  return context.agent?.session?.header?.cwd
}

function memoryPath(workspace, fileName) {
  const root = resolve(workspace)
  const path = resolve(root, fileName)
  if (relative(root, path).startsWith(`..${sep}`) || relative(root, path) === '..') {
    throw new Error('MEMORY.md path must remain inside the workspace')
  }
  return path
}

function readMemory(workspace, config) {
  if (!workspace) return { path: undefined, text: '', truncated: false, updatedAt: undefined }
  const path = memoryPath(workspace, config.fileName)
  try {
    const raw = readFileSync(path, 'utf8')
    const text = raw.slice(0, config.maxChars)
    return { path, text, truncated: raw.length > text.length, updatedAt: statSync(path).mtime.toISOString() }
  } catch (error) {
    if (error?.code === 'ENOENT') return { path, text: '', truncated: false, updatedAt: undefined }
    throw error
  }
}

function readMemorySync(workspace, config) {
  return readMemory(workspace, config)
}

function scoreLine(line, terms) {
  const lower = line.toLowerCase()
  return terms.reduce((score, term) => score + (lower.includes(term) ? 1 : 0), 0)
}

function relevantExcerpt(text, query, maxMatches) {
  const terms = query.toLowerCase().split(/[^\p{L}\p{N}_-]+/u).filter((term) => term.length > 1)
  if (!terms.length) return text
  const matches = text.split('\n').map((line, index) => ({ line, index, score: scoreLine(line, terms) }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .slice(0, maxMatches)
    .sort((a, b) => a.index - b.index)
  return matches.map(({ line, index }) => `${index + 1}: ${line}`).join('\n')
}

function textOf(content) {
  if (typeof content === 'string') return content
  if (!Array.isArray(content)) return ''
  return content.filter((block) => block?.type === 'text' && typeof block.text === 'string').map((block) => block.text).join('\n')
}

function candidateFrom(text) {
  const content = text.replace(/\s+/gu, ' ').trim()
  if (!content) return []
  return [content.slice(0, 500)]
}

function candidatePath(workspace, config) {
  return memoryPath(workspace, config.candidateFileName)
}

function candidateCount(text) {
  return (text.match(/^\- \[ \]/gm) ?? []).length
}

function appendCandidates(workspace, candidates, config) {
  if (!workspace || candidates.length === 0) return 0
  const path = candidatePath(workspace, config)
  let existing = ''
  try { existing = readFileSync(path, 'utf8') } catch (error) { if (error?.code !== 'ENOENT') throw error }
  const remaining = Math.max(0, config.maxCandidates - candidateCount(existing))
  if (remaining === 0) return 0
  const known = new Set(existing.split('\n').map((line) => line.replace(/^\- \[ \] /, '').trim()))
  const additions = candidates.filter((candidate) => !known.has(candidate)).slice(0, remaining)
  if (!additions.length) return 0
  const header = existing ? '' : '# Memory Candidates\n\n> Auto-captured candidates. Move only reviewed facts into MEMORY.md.\n\n'
  const body = additions.map((candidate) => `- [ ] ${candidate}`).join('\n') + '\n'
  const next = `${header}${body}`
  if (existing.length + next.length > config.maxCandidateChars) return 0
  appendFileSync(path, next)
  return additions.length
}

export function apply(ctx, config) {
  const scanned = new Map()
  ctx.effect(() => ctx.systemPrompt.context({
    name: 'project-memory',
    order: -20,
    text: (context) => {
      const workspace = workspaceOf(context)
      const { path, text, truncated, updatedAt } = readMemorySync(workspace, config)
      if (!text) return ''
      const warning = truncated ? '\n[Memory file truncated by the configured character limit.]' : ''
      return `Project memory (human-maintained; source: ${path}; updated: ${updatedAt}). Follow it as durable project context. Do not claim it was generated by you.${warning}\n\n${text}`
    },
  }))

  ctx.tools.register(defineTool({
    name: 'project_memory',
    description: 'Read relevant, human-maintained project memory from MEMORY.md. Use this before asking for facts that may have been established in earlier work. This tool never writes memory; propose edits in your response for human review.',
    parameters: {
      query: { type: 'string', required: true, description: 'Facts, decision, component, or task to look up.' },
    },
    output: {
      schema: { type: 'object', properties: { found: { type: 'boolean' }, path: { type: 'string' }, excerpt: { type: 'string' }, truncated: { type: 'boolean' }, updatedAt: { type: 'string' } }, additionalProperties: false },
      render: (_args, value) => [{ type: 'text', text: value.found ? `Project memory (${value.path}):\n${value.excerpt}` : 'No project memory file or matching memory was found.' }],
    },
    async execute(args, exec) {
      const workspace = exec.agent.session?.header?.cwd
      const { path, text, truncated, updatedAt } = readMemory(workspace, config)
      const excerpt = relevantExcerpt(text, args.query, config.maxMatches)
      return { found: excerpt.length > 0, path: path ?? '', excerpt, truncated, updatedAt: updatedAt ?? '' }
    },
  }))

  // Lazy mode captures every new user message verbatim as a proposal candidate.
  // It never writes MEMORY.md; a human reviews candidates and moves facts over.
  if (config.lazyMode) ctx.on('agent/turn-stopping', (payload) => {
    const agent = payload.agent
    const workspace = agent?.session?.header?.cwd
    if (!workspace) return
    const sessionId = agent.session.id
    const after = scanned.get(sessionId) ?? 0
    const events = agent.session.events.filter((event) => event.seq > after)
    const candidates = events.filter((event) => event.type === 'user/message' && event.data?.source?.kind === 'user')
      .flatMap((event) => candidateFrom(textOf(event.data?.content)))
    const latest = agent.session.events.at(-1)?.seq ?? after
    scanned.set(sessionId, latest)
    appendCandidates(workspace, candidates, config)
  })
}
